In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# !pip install spacy
# !pip install langid

import numpy as np
import pandas as pd
import spacy # fast NLP
pd.set_option("display.precision", 2)
pd.set_option('display.max_columns', None)

     |████████████████████████████████| 1.9MB 11.7MB/s 
  Created wheel for langid: filename=langid-1.1.6-cp37-none-any.whl size=1941191 sha256=bc176c68173207c92b7b15c7cbc17f6c145f992618b08e96ab3591672726281b
  Stored in directory: /root/.cache/pip/wheels/29/bc/61/50a93be85d1afe9436c3dc61f38da8ad7b637a38af4824e86e
Successfully built langid


## Removing non-english tweets using ASCII filtering

In [ ]:
# check for non-ascii (standard English 256 characters) entries 
# def check_ascii(x):
#   if str(x).isascii():
#     return x
#   else:
#     return pd.NA

# tweet_headers = ['user_id', 'tweet_id', 'tweet', 'created_at']
# # polluter (spam/bot) tweets
# polluter_tweet_df = pd.read_csv('/content/drive/Shareddrives/CSCI 5523 Group Project/Data/content_polluters_tweets.txt', delimiter='\t', names=tweet_headers)
# # actual user tweets
# legitimate_tweet_df = pd.read_csv('/content/drive/Shareddrives/CSCI 5523 Group Project/Data/legitimate_users_tweets.txt', delimiter='\t', names=tweet_headers)

# # filter out non-ascii (non-English) entries
# checked_tweets = polluter_tweet_df['tweet'].apply(check_ascii)
# polluter_tweet_df['tweet'] = checked_tweets
# polluter_tweet_df_filtered = polluter_tweet_df.dropna(axis = 0)
# polluter_tweet_df_filtered['label'] = 1

# checked_tweets = legitimate_tweet_df['tweet'].apply(check_ascii)
# legitimate_tweet_df['tweet'] = checked_tweets
# legitimate_tweet_df_filtered = legitimate_tweet_df.dropna(axis = 0)
# legitimate_tweet_df_filtered['label'] = 0

In [ ]:
# print(polluter_tweet_df_filtered.shape)
# print(legitimate_tweet_df_filtered.shape)

In [ ]:
# polluter_tweet_df_filtered.to_csv("/content/drive/Shareddrives/CSCI 5523 Group Project/Data/content_polluters_tweets_filtered.csv", index = False)
# legitimate_tweet_df_filtered.to_csv("/content/drive/Shareddrives/CSCI 5523 Group Project/Data/legitimate_users_tweets_filtered.csv", index = False)

# Load CSVs into DataFrames

In [ ]:
# polluter_account_headers = ['user_id', 'created_at', 'collected_at', 'following_count', 'follower_count', 'tweet_count', 'screen_name_length', 'user_description_length']
# polluter_account_df = pd.read_csv('/content/drive/Shareddrives/CSCI 5523 Group Project/Data/content_polluters.txt', delimiter="\t", names=polluter_account_headers)
# polluter_account_df.head()

In [ ]:
# legitimate_account_headers = ['user_id', 'created_at', 'collected_at', 'following_count', 'follower_count', 'tweet_count', 'screen_name_length', 'user_description_length']
# legitimate_account_df = pd.read_csv('/content/drive/Shareddrives/CSCI 5523 Group Project/Data/legitimate_users.txt', delimiter="\t", names=polluter_account_headers)
# legitimate_account_df.head()

In [ ]:
polluter_tweet_df = pd.read_csv('/content/drive/Shareddrives/CSCI 5523 Group Project/Data/content_polluters_tweets_filtered.csv')
print(polluter_tweet_df.shape)
polluter_tweet_df.head()

(2149828, 5)


user_id    tweet_id                                              tweet  \
0     6301  5599519501  MELBOURNE ENQUIRY: Seeking a variety of acts f...   
1     6301  5600313663  THE BURLESQUE BOOTCAMP SYDNEY - Open Date tick...   
2     6301  5600328557  THE BURLESQUE BOOTCAMP SYDNEY - Open Date tick...   
3     6301  5600338093  THE BURLESQUE BOOTCAMP SYDNEY - Open Date tick...   
4     6301  5600564863  Come to "The Burlesque Bootcamp - Sydney" Satu...   

            created_at  label  
0  2009-11-10 15:14:31      1  
1  2009-11-10 15:46:05      1  
2  2009-11-10 15:46:40      1  
3  2009-11-10 15:47:03      1  
4  2009-11-10 15:56:03      1

In [ ]:
legitimate_tweet_df = pd.read_csv('/content/drive/Shareddrives/CSCI 5523 Group Project/Data/legitimate_users_tweets_filtered.csv')
print(legitimate_tweet_df.shape)
legitimate_tweet_df.head()

(2410899, 5)


user_id    tweet_id                                              tweet  \
0      614  5873834688  I wish I had more free time. I'd LOVE to see you!   
1      614  5873809295           Tonight, tomorrow. On the plane at 5 pm.   
2      614  5291252160  I'm at Carlucci's in Salt Lake City, UT http:/...   
3      614  5205651441                               @spam @JannetteDavid   
4     1038  5762418891  @dialupkid Mijn vriendin en ik hebben een geza...   

            created_at  label  
0  2009-11-19 18:16:40      0  
1  2009-11-19 18:15:42      0  
2  2009-10-30 11:24:52      0  
3  2009-10-27 12:17:35      0  
4  2009-11-16 05:08:29      0

In [ ]:
legitimate_tweet_sample_df = legitimate_tweet_df[['tweet', 'label']].sample(frac=0.1)
polluter_tweet_sample_df = polluter_tweet_df[['tweet', 'label']].sample(frac=0.1)
sample_df = legitimate_tweet_sample_df.append(polluter_tweet_sample_df)
sample_df.head()

# # get the language id for each text
# ids_langid = training_df['tweet'].apply(langid.classify)

# # get just the language label
# langs = ids_langid.apply(lambda tuple: tuple[0])

# # how many unique language labels were applied?
# print("Number of tagged languages (estimated):")
# print(len(langs.unique()))

# # percent of the total dataset in English
# print("Percent of data in English (estimated):")
# print((sum(langs=="en")/len(langs))*100)

tweet  label
279786   Headig to Tang Soo Do then it's time to relax ...      0
668128   I don't think there was enough to over turn th...      0
101210   @sacca Congrats! How often did you think about...      0
945188   A UTOPIA DA MELHOR IDADE (CPFL CUltura)http://...      0
1436452  :: Blank stare at Diddy's video:: sooo he's tr...      0

# Preprocessing Steps

Remove empty/blank entries

In [ ]:
sample_df.dropna(inplace=True)
sample_df = sample_df[sample_df.tweet != '']
sample_df.describe()

label
count  456073.00
mean        0.47
std         0.50
min         0.00
25%         0.00
50%         0.00
75%         1.00
max         1.00

Drop null values, only consider 20,000 random tweets as a precaution for performance. Hughdan will adjust this later.

In [ ]:
sample_df = sample_df.sample(frac=1).head(20000)
sample_df.head()

tweet  label
231489   Engadget for iPhone/ iPod Touch http://bit.ly/...      1
905683   Oh bless me lord for I have sinned. It's been ...      0
1678297               This is coming from thetweettank.com      1
862885   cum on guys from america i need to talk to som...      1
56854    RT @Eb_the_Celeb: Wait??? Who sags anymore 4 M...      0

Remove Punctuation

In [ ]:
import re

sample_df['tweet'] = sample_df['tweet'].apply(lambda x: re.sub('[^a-zA-z0-9\s]','',x))
sample_df.dropna(inplace=True)
sample_df = sample_df[sample_df.tweet != '']
sample_df.describe()

label
count  19997.00
mean       0.47
std        0.50
min        0.00
25%        0.00
50%        0.00
75%        1.00
max        1.00

Convert to lowercase

In [ ]:
sample_df['tweet'] = sample_df['tweet'].apply(lambda x: x.lower())

# Create 2-grams

In [ ]:
words = []
for ii in range(0,len(sample_df)):
    words.append(str(sample_df.iloc[ii]['tweet']).split(" "))

n_gram_all = []

for word in words:
    # get n-grams for the instance
    n_gram = []
    for i in range(len(word)-2+1):
        n_gram.append("".join(word[i:i+2]))
    n_gram_all.append(n_gram)
    
n_gram_all[0][:10]


['engadgetfor',
 'foriphone',
 'iphoneipod',
 'ipodtouch',
 'touchhttpbitly5wje1i',
 'httpbitly5wje1i^ns']

# Vectorizing with Hashing Vectorizer

In [ ]:
from sklearn.feature_extraction.text import HashingVectorizer

# hash vectorizer instance
hvec = HashingVectorizer(lowercase=False, analyzer=lambda l:l, n_features=2**12)

# features matrix X
X = hvec.fit_transform(n_gram_all)
print(X)

  (0, 218)	0.4082482904638631
  (0, 569)	0.4082482904638631
  (0, 1210)	-0.4082482904638631
  (0, 1704)	-0.4082482904638631
  (0, 1890)	0.4082482904638631
  (0, 2031)	-0.4082482904638631
  (1, 276)	0.2581988897471611
  (1, 1023)	0.2581988897471611
  (1, 1839)	-0.2581988897471611
  (1, 2099)	0.2581988897471611
  (1, 2128)	-0.2581988897471611
  (1, 2217)	0.2581988897471611
  (1, 2358)	0.2581988897471611
  (1, 2568)	0.2581988897471611
  (1, 2970)	0.2581988897471611
  (1, 3341)	0.2581988897471611
  (1, 3439)	-0.2581988897471611
  (1, 3466)	0.2581988897471611
  (1, 3620)	-0.2581988897471611
  (1, 3626)	0.2581988897471611
  (1, 4090)	0.2581988897471611
  (2, 497)	-0.5
  (2, 1072)	0.5
  (2, 3067)	0.5
  (2, 3913)	-0.5
  :	:
  (19994, 16)	-0.2773500981126146
  (19994, 657)	-0.2773500981126146
  (19994, 778)	0.2773500981126146
  (19994, 1394)	0.2773500981126146
  (19994, 1766)	0.2773500981126146
  (19994, 2062)	0.2773500981126146
  (19994, 2705)	-0.2773500981126146
  (19994, 3085)	0.277350098112

## Build Training and Testing Datasets

In [ ]:
from sklearn.model_selection import train_test_split

# test set size of 20% of the data and the random seed 1
X_train, X_test, y_train, y_test = train_test_split(X.toarray(), sample['label'], test_size=0.2, random_state=1)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
# for large datasets use a train-test split index array
split_idx = np.arange(dataset_sample.shape[0])
np.random.seed(0)
np.random.shuffle(split_idx)
split = 8*dataset_sample.shape[0]//10 # 20% train-test split
train_idx = split_idx[:split]
test_idx = split_idx[split:]

X_train = X[train_idx]
X_test = X[test_idx]
y_train = dataset_sample['label'].iloc[train_idx]
y_test = dataset_sample['label'].iloc[test_idx]